---
- name: activate rescue mode
  ansible.builtin.uri:
    url: "https://robot-ws.your-server.de/boot/{{ ansible_default_ipv4.address }}/rescue"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "os=linux&arch=64&authorized_key={{ hetzner_installimage_key_fingerprint }}"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  when: hetzner_installimage_rescue.json.rescue.active == false

- name: do first reboot host
  ansible.builtin.reboot:

- name: remove server from local known_hosts file
  ansible.builtin.shell: ssh-keygen -R {{ ansible_default_ipv4.address }}
  when: hetzner_installimage_purge_ssh_known_hosts
